### PR TITLE
Updated items/locations

### PR DESCRIPTION
**Pull request by Br00ty**
added a few new items and locations that should just work no problem.

### CODE REVIEW

**Comment by Marechal-L** [comment]
I suggest to let this pull-request open for now so we could modify it just in case we will discover other items during the first weeks of the official release

**Comment by Br00ty** [comment]
Agreed, I just added more location/items/requirements as of 8/17

**Comment by Marechal-L** [comment]
Thanks for the update.
I'll merge this first step

**Comment by Br00ty** [comment]
awesome!!! sounds great!

**Pull request merged**
