### PR TITLE
DS3: December DLC Additions Fixes

### PR DESCRIPTION
**Pull request by Br00ty**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?

This is fixing item counts for DLC, and this adds location rules for Painted World and Ringed City, as those locations need keys. Speaking of the keys, I added those to the pool as well, and added their respective location. This should be good and ready to roll

## How was this tested?
Generation after generation after generation after generation of success

### CODE REVIEW

**Comment by Br00ty** [comment]
this should be more than 100% now, ive got seed generation including DLC into the important location pool now :D

**Comment by Br00ty** [comment]
i saw the comment the guy made about the wrong Estus shard counts, so i went ahead and fixed that and included that in this PR.

**Comment by Marechal-L** [comment]
I was ready to merge this PR but
Unfortunately by changing the Estus shard counts you also changed the order of the IDs, breaking the backward compatibility of the previous seeds.
Can you please revert it ? :/ 

A way to fix the count would be to exclude theses locations/items from the pool and not from the tables itself.

**Comment by Br00ty** [comment]
Thats my apologies, i quickly forgot about backwards compatibility lol. i reverted the last two commits, and ill let you handle the estus shard count

**Pull request merged**
